### ISSUE TITLE
backend not found

### ISSUE THREAD

**Issue by shalaby** [ezze/ezze-elfinder#1]
i did exactly what you said, and it gives me this message "Unable to connect to backend. backend not found.", i created a controller and inside it the actions function, and the fileUploader action.

**Comment by ezze** [comment]
Dear, shalaby.

The mentioned error means that ElFinder is unable to receive an answer from files' uploading script (so-called connector). Please, make sure that you specify a valid URL to connector's action in widget's call (`connectorRoute` parameter). For example, if your controller is `site` (`SiteController` class) and your connector's action is `uploaderConnector` (specified as key of an array in `actions()` method) then your widget's call will look like this:

```
$this->widget("ext.ezzeelfinder.ElFinderWidget", array(
    'selector' => "...",
    'clientOptions' => array(
        ...
    ),
    'connectorRoute' => "site/uploaderConnector",
    'connectorOptions' => array(
        'roots' => array(
            array(
                ...
            )
        )
    )
));
```

In my example controller's name is `admin` (`AdminController` class) and connector's action is `fileUploaderConnector`. That's why my widget's `controllerRoute` is `admin/fileUploaderConnector`.

Please let me know if this helps.

**Comment by ezze** [comment]
Closed due to it hasn't any details from issue's author.
